// Copyright 2023-2024 BasicallyIAmFox
// 
//    Licensed under the CLA (the "License")
//    See LICENSE.txt for more info.

namespace CollectionEqualityGenerator;

public static class Constants {
	public const string AutoGeneratedComment = "";
}
